
$('#submit').click(function() {
  // https://gist.github.com/6174/6062387
	
  var radioValue = $("input[name='mode']:checked").val();
  var meetID = $("input#meetID").val();
  console.log(meetID);
  console.log(radioValue);
  console.log(randMeetName);
	getMeetTeams(meetID, radioValue);
});

function postData(url, callbackParam) {
    var params = { 
    "__CALLBACKPARAM":"NONE",
    "__CALLBACKID": "__Page",
    "__VIEWSTATEGENERATOR": "", 
    "__VIEWSTATE": "", 
    "__EVENTARGUMENT":"",
    "__EVENTTARGET":""
  }
  params["__CALLBACKPARAM"] = callbackParam
  $.post(url, params, function(data, status) {
    console.log(data);
	//listID = r.split('<input id="listID" type="hidden" value="')[1].split('"',1)[0]
  })
}
function updateList(url, teamID) {

}
function createList(url, sport) {
	var listName = Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
	param = `UpdateAddList⌂0⌂${listName}⌂AUTOGENERATED⌂${sport}⌂1⌂1⌂0⌂0⌂0`;
	listID = postData(url, param);
}

function extractJson(source) {
	var rawTeamData = /constant\("initialData", (.+)\);/.exec(source);
	var rawTokenData = /constant\("params", (.+)\)/.exec(source);
	return [JSON.parse(rawTeamData[1]), JSON.parse(rawTokenData[1])]
}
function getMeetTeams(meetID, modeLetter) {
  var mode = "CrossCountry";
  if (modeLetter == "T") {
    mode = "TrackAndField";
  }
var url = `https://www.athletic.net/${mode}/meet/${meetID}/teams`;
  console.log(url);
	fetch("https://allorigins.me/get?url=" + url).then(function(response) {
        return response.json();
    }).then((data) => {
		  var [teamData, _] = extractJson(data["contents"]);
		  console.log(teamData["teams"]);
		let modifyURL = "https://www.athletic.net/Edit/General/CustomLists.aspx?SchoolID=13318&Sport=${mode}";
		createList(modifyURL, mode);
		for team in teamData["teams"] {
			updateList(modifyURL, team["ID"]);
		}
		//createList(
  })
}
